"""agrego relaciones y nuevas tablas

Revision ID: 7dde3c66d419
Revises: b61b924a4cc3
Create Date: 2025-11-09 12:19:28.413883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dde3c66d419'
down_revision = 'b61b924a4cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destacado_destino',
    sa.Column('destacado_id', sa.Integer(), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['destino_id'], ['destino.destino_id'], ),
    sa.PrimaryKeyConstraint('destacado_id')
    )
    op.create_table('incluye_destino',
    sa.Column('incluye_id', sa.Integer(), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['destino_id'], ['destino.destino_id'], ),
    sa.PrimaryKeyConstraint('incluye_id')
    )
    op.create_table('itinerario_paquete',
    sa.Column('itinerario_id', sa.Integer(), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=True),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['destino_id'], ['destino.destino_id'], ),
    sa.PrimaryKeyConstraint('itinerario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itinerario_paquete')
    op.drop_table('incluye_destino')
    op.drop_table('destacado_destino')
    # ### end Alembic commands ###
