"""initial

Revision ID: b61b924a4cc3
Revises: 
Create Date: 2025-11-08 21:42:07.525760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b61b924a4cc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aerolinea', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'pais', ['pais_id'], ['pais_id'])

    with op.batch_alter_table('aeropuerto', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'provincia', ['provincia_id'], ['provincia_id'])

    with op.batch_alter_table('destino', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'provincia', ['provincia_id'], ['provincia_id'])

    with op.batch_alter_table('imagen_alojamiento', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('imagen_alojamiento_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'alojamiento', ['alojamiento_id'], ['alojamiento_id'])

    with op.batch_alter_table('imagen_destino', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('imagen_destino_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'destino', ['destino_id'], ['destino_id'])

    with op.batch_alter_table('provincia', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'pais', ['pais_id'], ['pais_id'])

    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('fecha_fin',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('pasajeros',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('precio_total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('contrasena',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('creado',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('creado',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('contrasena',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=False)

    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('precio_total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('pasajeros',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_fin',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('provincia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('imagen_destino', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('imagen_destino_ibfk_1'), 'destino', ['destino_id'], ['destino_id'], ondelete='CASCADE')

    with op.batch_alter_table('imagen_alojamiento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('imagen_alojamiento_ibfk_1'), 'alojamiento', ['alojamiento_id'], ['alojamiento_id'], ondelete='CASCADE')

    with op.batch_alter_table('destino', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('aeropuerto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('aerolinea', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
