"""update vuelo y relaciones paquete-vuelo

Revision ID: ecdc4b4d0e86
Revises: 7dde3c66d419
Create Date: 2025-11-09 13:27:55.159564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecdc4b4d0e86'
down_revision = '7dde3c66d419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paquete_vuelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=True),
    sa.Column('vuelo_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['destino_id'], ['destino.destino_id'], ),
    sa.ForeignKeyConstraint(['vuelo_id'], ['vuelo.vuelo_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vuelo_ida_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vuelo_vuelta_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('reserva_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'vuelo', ['vuelo_vuelta_id'], ['vuelo_id'])
        batch_op.create_foreign_key(None, 'vuelo', ['vuelo_ida_id'], ['vuelo_id'])
        batch_op.drop_column('vuelo_id')

    with op.batch_alter_table('vuelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origen_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('destino_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('vuelo_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('vuelo_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'aeropuerto', ['origen_id'], ['aeropuerto_id'])
        batch_op.create_foreign_key(None, 'aeropuerto', ['destino_id'], ['aeropuerto_id'])
        batch_op.drop_column('destino')
        batch_op.drop_column('origen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vuelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origen', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('destino', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vuelo_ibfk_3'), 'destino', ['destino'], ['destino_id'])
        batch_op.create_foreign_key(batch_op.f('vuelo_ibfk_2'), 'aeropuerto', ['origen'], ['aeropuerto_id'])
        batch_op.drop_column('destino_id')
        batch_op.drop_column('origen_id')

    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vuelo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reserva_ibfk_3'), 'vuelo', ['vuelo_id'], ['vuelo_id'])
        batch_op.drop_column('vuelo_vuelta_id')
        batch_op.drop_column('vuelo_ida_id')

    op.drop_table('paquete_vuelo')
    # ### end Alembic commands ###
